image: ghcr.io/p2p-org/cosmos-heighliner
imageTag: saga-v0.4.0
# Required for the new chart - toolkit image used for init containers and healthcheck sidecar
toolkitImage: ghcr.io/p2p-org/cosmos-heighliner
toolkitImageTag: saga-v0.4.0
replicas: 1
# Note: service.ports configuration is required by the new chart but will use defaults from values.yaml if not specified
storage:
  data: 6144Gi
  config: "5Gi"
nodeSelectorKey: ssc-1
monitoring:
  publicRpcEndpoint: https://saga-rpc.polkachu.com
blch:
  minGasPrice: 0.01usaga
  nodeType: archive
  binary: sscd
  id: ssc-1
  homeDir: .ssc
  genesisURL: https://github.com/p2p-org/devops-tendermint-public/releases/download/genesis-collection/genesis-saga-mainnet.json
  snapshotURL: https://snapshots.polkachu.com/snapshots/saga/saga_6555530.tar.lz4
  config:
    peers: f78dac64f29217c91328a62c0e691b2c37000a30@178.23.126.103:26656,d47ac0343d28c53fe22c94a2df8100fbe682eea2@57.128.98.34:26656,3803d12cc467d1d389036fa242ac6e3a89d1646a@173.234.17.237:26656,a91477804bdeb8ee837c56b3dc3f8188423c398a@80.64.208.199:26656,fefc6b50a5748749a58ee18cf0d566c0f96ba180@141.94.160.62:36656,4dedf23186b5c22294249571652a40b32e263b39@37.59.22.147:26656,b2b84afbe50ab07df9378c45a638d144b6c471c6@135.181.220.33:26656,9c1733a8a7832f5813d14d500362ab1c449d28c7@16.63.103.144:26656,054b42595365063100789a218070023bb749c156@66.172.36.135:11156,4318a1fafa158df21b98d28bf5ed529f79db57c7@95.216.38.96:11156
    overrides: |-
      [tx_index]
      indexer = "kv"
  network: mainnet
endpoints:
  rpc:
    ingressName: saga-mainnet-rpc
    host: saga-mainnet-archive.tm.p2p.org
    tlsHost: saga-mainnet-archive.tm.p2p.org
    tlsSecretName: saga-mainnet-archive.tm.p2p.org-tls
  grpc:
    ingressName: saga-mainnet-grpc
    host: grpc-saga-mainnet-archive.tm.p2p.org
    tlsHost: grpc-saga-mainnet-archive.tm.p2p.org
    tlsSecretName: grpc-saga-mainnet-archive.tm.p2p.org-tls
restartNode:
  enabled: true
  cronJobSchedule: 0 12 * * MON
archiveBackup:
  enabled: true
