{{- if not .Values.useGatewayAPI }}
{{- range $key, $val := .Values.endpoints }}
{{- $enabled := default true $val.enabled }}
{{- if $enabled }}
{{- $servicePort := $val.servicePort }}
{{- if not $servicePort }}
{{- if eq $key "rpc" }}
{{- $servicePort = $.Values.service.ports.rpc.port }}
{{- else if eq $key "grpc" }}
{{- $servicePort = $.Values.service.ports.grpc.port }}
{{- else if eq $key "ws" }}
{{- $servicePort = $.Values.service.ports.ws.port }}
{{- else if eq $key "rest" }}
{{- $servicePort = $.Values.service.ports.rest.port }}
{{- else }}
{{- $servicePort = $.Values.service.ports.rpc.port }}
{{- end }}
{{- end }}
{{- $name := printf "%s-%s" $.Release.Name $key }}
{{- $host := include "host" (dict "context" $ "endpointName" $key) }}
{{- $tlsSecretName := printf "%s-%s" $host "tls" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ default $name $val.ingressName }}-nlb
  labels:
{{ include "blch-node.labels" $ | nindent 4 }}
  {{- if or $val.additionalIngressAnnotations $.Values.basicAuth.enabled }}
  annotations:
    {{- with $val.additionalIngressAnnotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    {{- if $.Values.basicAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "{{ $.Release.Name }}-basic-auth"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Login"
    {{- end }}
  {{- end }}
spec:
  ingressClassName: nginx-nlb
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
        {{- if kindIs "slice" $val.path }}
        {{- range $val.path }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Release.Name }}-rpc
                port:
                  number: {{ default $servicePort .servicePort }}
        {{- end }}
        {{- else }}
          - path: {{ default "/" $val.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $.Release.Name }}-rpc
                port:
                  number: {{ $servicePort }}
        {{- end }}
  tls:
  - hosts:
    - {{ default $host $val.tlsHost | quote }}
    secretName: {{ default $tlsSecretName $val.tlsSecretName }}
{{- end }}
{{- end }}
{{- end }}
