{{- if .Values.publishSnapshot.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-public-snapshot
  labels:
  {{ include "blch-node.labels" . | nindent 4 }}
spec:
   type: ExternalName
   externalName: {{ .Values.publishSnapshot.baseDomain }}
   ports:
     - port: 443
       targetPort: 443
{{- end }}
