{{- if .Values.publishSnapshot.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshots-bucket-{{ .Release.Name }}
  labels:
  {{ include "blch-node.labels" . | nindent 4 }}
{{- end }}
