apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rpc
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "blch-node.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.publishSvcDuringSync }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: rpc
      port: {{ .Values.service.ports.rpc.port }}
      targetPort: rpc
      protocol: {{ .Values.service.ports.rpc.protocol }}
    - name: grpc
      port: {{ .Values.service.ports.grpc.port }}
      targetPort: grpc
      protocol: {{ .Values.service.ports.grpc.protocol }}
    - name: rest
      port: {{ .Values.service.ports.rest.port }}
      targetPort: rest
      protocol: {{ .Values.service.ports.rest.protocol }}
    - name: ws
      port: {{ .Values.service.ports.ws.port }}
      targetPort: ws
      protocol: {{ .Values.service.ports.ws.protocol }}
  selector:
    {{- include "blch-node.labels" . | nindent 4 }}
{{ range $i := until (int .Values.replicas) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-p2p-{{ $i }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "blch-node.labels" $ | nindent 4 }}
  {{- if or $.Values.p2pDNSNameEnabled $.Values.service.p2p.annotations }}
  annotations:
  {{- with $.Values.service.p2p.annotations  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.p2pDNSNameEnabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ $.Release.Name }}-{{ $i }}.{{ $.Values.endpointsBaseDomain }}
  {{- end }}
  {{- end }}
spec:
  type: {{ $.Values.service.p2p.type }}
  {{- with $.Values.service.p2p.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $.Values.service.p2p.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: p2p
      port: {{ $.Values.service.p2p.port }}
      targetPort: {{ $.Values.service.p2p.containerPort }}
      protocol: {{ $.Values.service.p2p.protocol }}
  selector:
    {{- include "blch-node.labels" $ | nindent 4 }}
    app.kubernetes.io/instance: {{ $.Release.Name }}-{{ $i }}
{{- end }}
